services:
  api:
    build:
      context: ./../../backend
    env_file:
      - ./../../backend/.env.local
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: ./../../frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/v1
    ports:
      - "3000:3000"

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7

volumes:
  mongo_data:
