services:
  backend:
    build:
      context: ../../backend
    env_file: .env
    volumes:
      - app_data:/app/data
      - logs_data:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ../../frontend
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/v1
    volumes:
      - node_modules_cache:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:8.0
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
    ports:
      - "27017:27017"

  redis:
    image: redis:8.2
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  redis_data:
  app_data:
  logs_data:
  node_modules_cache:
