version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env              # локальные переменные (например, DEBUG, database_url)
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://localhost:8000    # фронтенд будет обращаться к локальному API
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5s
      retries: 5
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "redispass"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
  worker:
    build: ./backend
    command: celery -A app.workers.tasks worker --loglevel=info
    depends_on:
      - backend
      - redis
