name: CI Pipeline

on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports: [5432:5432]
      redis:
        image: redis:7
        ports: [6379:6379]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt
      - name: Run backend tests
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379
        run: pytest backend/app/tests -q
      - name: Install frontend dependencies
        run: npm ci --prefix frontend
      - name: Run frontend build
        run: npm run build --prefix frontend
      - name: Run frontend lint & tests
        run: npm run test --prefix frontend
